min_x: -1000
min_z: -1000

max_x: 1000
max_z: 1000

max_threads: 20 # Depends on your CPU, if the server seems to lag/crash, decrease this value, Less threads = Slower process, More threads = Faster if there's enough hardware resources

frequency: 0.01 # Smaller number = Bigger regions
jitter: 0.5 # 0 will create exactly square-shaped regions, increasing this will make regions more un-even, note that if you increase it too much it may randomly create very small or very big regions

small_cluster_skip: 2000

# Used for region names
types:
  plains:
    - PLAINS
    - SUNFLOWER_PLAINS
  artic:
    - SNOWY_PLAINS
    - SNOWY_BEACH
    - SNOWY_SLOPES
    - SNOWY_TAIGA
  desert:
    - DESERT